### ISSUE TITLE
Allow purging via source location

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cache-flush#40]
In addition to the observation event, it should be possible to trigger a cache flush using just a source-location.

eg:

```
{
  "owner": "adobe",
  "repo": "theblog",
  "ref": "master",
  "sourceLocation": "https://blog.adobe.com/scripts/main.js"
}
```

with https://github.com/adobe/helix-publish/issues/569 in place, it would allow to purge the respective fastly sercices.

**Comment by trieloff** [comment]
sourceLocation only covers the inner cdn, which is purged with the surrogate key from adobe/helix-publish#569 (`https://theblog--adobe.hlx.page/scripts/main.js`).

we also need a parameter `url` for the outer cdn `https://blog.adobe.com/scripts/main.js` to be purged with a `PURGE` request.

**Comment by tripodsan** [comment]
yes...both. `sourceLocation: ['https://theblog--adobe.hlx.page/scripts/main.js', 'https://blog.adobe.com/scripts/main.js' ]`
